### ISSUE TITLE
Добавить обработку кода -1020 (отсутствие интернета)

### ISSUE THREAD

**Issue by ZaytsevaMarina** [surfstudio/NodeKit#110]
Например, на моем айфоне, Surf-приложения с NodeKit не показывают ошибки отсутствия интернета, поскольку этот кейс падает не в -1009 код, а в -1020. Единственное, что я нашла по этой теме - [тут](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/497)

**Comment by chausovSurfStudio** [comment]
Добавлено в рамках https://github.com/surfstudio/NodeKit/pull/112, будет в версии 3.4.0
