### ISSUE TITLE
Ability model to Observer 

### ISSUE THREAD

**Issue by daukabase** [surfstudio/NodeKit#58]
As I understood there is no ability to add local model to Observer. To my mind, it would be greate. 

Example, 
```
let observer = chain.process(EmptyModel()) // type is Observer<T>
```

I want to add model for our Observer
```
let value: T?
observer.accept(value) // something like that c:
```

And it will return my value
```
observer.onCompleted { value: T in
//do something with value
}
```

**Comment by LastSprint** [comment]
You can use Observer.emit(data: “value”)
